packages:
  - "apps/*"
  - "libs/*/*"
  - "libs/shared/*"
  - "libs/shared/*/*"
  - "!**/node_modules/**"
  - "!**/.next/**"
  - "!**/dist/**"
  - "!**/build/**"

shamefullyHoist: true
autoInstallPeers: true
saveExact: true
minimumReleaseAge: 0
strictDepBuilds: false

overrides:
  graphql: "16.12.0"
  form-data: ">=2.5.4"
  fast-xml-parser: ">=4.5.5"
  protobufjs: ">=7.5.5"

onlyBuiltDependencies:
  - serverless

allowBuilds:
  '0': protobufjs
  '1': serverless
  '@apollo/protobufjs': set this to true or false
  '@firebase/util': set this to true or false
  '@parcel/watcher': set this to true or false
  '@sentry-internal/node-cpu-profiler': set this to true or false
  '@sentry/cli': set this to true or false
  '@swc/core': set this to true or false
  core-js: set this to true or false
  esbuild: set this to true or false
  lefthook: set this to true or false
  protobufjs: set this to true or false
  serverless: set this to true or false
  sharp: set this to true or false
  type-graphql: set this to true or false
  unrs-resolver: set this to true or false
