/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  query TempAllMagazinesOnMagazinesList($page: Int!) {\n    tempAllMagazines(page: $page) {\n      totalCount\n      totalPages\n      magazines {\n        id\n        slug\n        title\n        summary\n        content\n        backgroundImageUrl\n        updatedAt\n        publishedAt\n        author {\n          id\n          name\n        }\n      }\n    }\n  }\n": typeof types.TempAllMagazinesOnMagazinesListDocument,
    "\n  query GetLlmSettingOnLlmSettingFormSection {\n    llmSetting {\n      id\n      endpoint\n      apiKeyMasked\n      model\n      thinkingLevel\n      updatedAt\n    }\n  }\n": typeof types.GetLlmSettingOnLlmSettingFormSectionDocument,
    "\n  mutation UpdateLlmSettingOnLlmSettingFormSection(\n    $endpoint: String\n    $apiKey: String\n    $model: String\n    $thinkingLevel: String\n  ) {\n    updateLlmSetting(\n      endpoint: $endpoint\n      apiKey: $apiKey\n      model: $model\n      thinkingLevel: $thinkingLevel\n    ) {\n      id\n      endpoint\n      apiKeyMasked\n      model\n      thinkingLevel\n      updatedAt\n    }\n  }\n": typeof types.UpdateLlmSettingOnLlmSettingFormSectionDocument,
    "\n  query CategoryBySlugOnCategoryPageMetadata($first: Int!, $locale: String!) {\n    categories(first: $first, locale: $locale) {\n      id\n      slug\n      labelKo\n      labelEn\n    }\n  }\n": typeof types.CategoryBySlugOnCategoryPageMetadataDocument,
    "\n  query ProductsForCompare($slug1: String!, $slug2: String!, $locale: String!) {\n    product1: productBySlug(slug: $slug1, locale: $locale) {\n      id\n      name\n      slug\n      summary\n      logoUrl\n      voteCount\n      tags {\n        id\n        name\n      }\n      ownedCompany {\n        name\n      }\n    }\n    product2: productBySlug(slug: $slug2, locale: $locale) {\n      id\n      name\n      slug\n      summary\n      logoUrl\n      voteCount\n      tags {\n        id\n        name\n      }\n      ownedCompany {\n        name\n      }\n    }\n  }\n": typeof types.ProductsForCompareDocument,
    "\n  query MagazineBySlugOnMagazinePageMetadata($slug: String!) {\n    magazineBySlug(slug: $slug) {\n      title\n      summary\n      backgroundImageUrl\n      publishedAt\n      updatedAt\n      author {\n        name\n      }\n    }\n  }\n": typeof types.MagazineBySlugOnMagazinePageMetadataDocument,
    "\n  query ProductsCountOnHomePage {\n    productsCount\n  }\n": typeof types.ProductsCountOnHomePageDocument,
    "\n  query ProductBySlugOnProductAlternativePageMetadata($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      name\n      summary\n      logoUrl\n      tags {\n        name\n      }\n      alternatives {\n        name\n        tags {\n          name\n        }\n      }\n    }\n  }\n": typeof types.ProductBySlugOnProductAlternativePageMetadataDocument,
    "\n  query ProductBySlugOnProductDetailPageMetadata($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      name\n      summary\n      logoUrl\n      description\n      tags {\n        name\n      }\n      ownedCompany {\n        name\n      }\n    }\n  }\n": typeof types.ProductBySlugOnProductDetailPageMetadataDocument,
    "\n  query AllCompaniesOnAllCompanyListTable($page: Int!) {\n    allCompanies(page: $page) {\n      totalCount\n      totalPages\n      companies {\n        id\n        name\n        type\n        address\n        startAt\n      }\n    }\n  }\n": typeof types.AllCompaniesOnAllCompanyListTableDocument,
    "\n  mutation CreateCompanyOnNewCompanyForm($input: CreateCompanyInput!) {\n    createCompany(input: $input) {\n      company {\n        id\n      }\n    }\n  }\n": typeof types.CreateCompanyOnNewCompanyFormDocument,
    "\n  mutation CreateMagazineOnWriteMagazine($input: CreateMagazineInput!) {\n    createMagazine(input: $input) {\n      magazine {\n        id\n        slug\n      }\n    }\n  }\n": typeof types.CreateMagazineOnWriteMagazineDocument,
    "\n  query MagazineBySlugOnInfoSection($slug: String!) {\n    magazineBySlug(slug: $slug) {\n      id\n      title\n      summary\n      backgroundImageUrl\n      publishedAt\n      author {\n        name\n      }\n    }\n  }\n": typeof types.MagazineBySlugOnInfoSectionDocument,
    "\n  query TempProductBySlugOnEditAlternativeProducts($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      alternatives {\n        id\n        name\n      }\n    }\n  }\n\n  query SearchProductsOnEditAlternativeProducts($query: String!) {\n    searchProducts(query: $query) {\n      id\n      name\n    }\n  }\n\n  mutation EditProductOnEditAlternativeProducts($input: UpdateAlternativeProductInput!, $slug: String!) {\n    updateAlternativeProduct(input: $input, slug: $slug) {\n      product {\n        id\n        alternatives {\n          id\n        }\n      }\n    }\n  }\n": typeof types.TempProductBySlugOnEditAlternativeProductsDocument,
    "\n  mutation RegisterProductCompanyOnEditProductCompany($input: RegisterProductCompanyInput!, $slug: String!) {\n    registerProductCompany(input: $input, slug: $slug) {\n      product {\n        id\n      }\n    }\n  }\n": typeof types.RegisterProductCompanyOnEditProductCompanyDocument,
    "\n  query SearchCompaniesOnEditProductCompany($query: String!) {\n    searchCompanies(query: $query) {\n      id\n      name\n    }\n  }\n": typeof types.SearchCompaniesOnEditProductCompanyDocument,
    "\n  query TempProductBySlugOnEditProductDescription($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      description\n    }\n  }\n\n  mutation EditProductOnEditProductDescription($input: EditProductInput!, $slug: String!) {\n    editProduct(input: $input, slug: $slug) {\n      product {\n        id\n        description\n      }\n    }\n  }\n": typeof types.TempProductBySlugOnEditProductDescriptionDocument,
    "\n  query FeatureOnEditProductFeatureItem($id: ID!) {\n    feature(id: $id) {\n      id\n      emoji\n      name\n      summary\n    }\n  }\n\n  mutation UpdateProductFeatureOnEditProductFeatureItem($input: UpdateProductFeatureInput!, $featureId: String!) {\n    updateProductFeature(input: $input, id: $featureId) {\n      feature {\n        id\n      }\n    }\n  }\n": typeof types.FeatureOnEditProductFeatureItemDocument,
    "\n  query TempProductBySlugOnEditProductInfo($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      name\n      summary\n    }\n  }\n\n  mutation EditProductOnEditProductInfo($input: EditProductInput!, $slug: String!) {\n    editProduct(input: $input, slug: $slug) {\n      product {\n        id\n        name\n        summary\n      }\n    }\n  }\n": typeof types.TempProductBySlugOnEditProductInfoDocument,
    "\n  fragment EditProductLinkItem on Link {\n    id\n    title\n    link\n    displayLink\n    iconUrl\n  }\n": typeof types.EditProductLinkItemFragmentDoc,
    "\n  mutation UpdateProductLinkOnEditProductLinkItem($slug: String!, $id: String!, $input: UpdateProductLinkInput!) {\n    updateProductLink(slug: $slug, id: $id, input: $input) {\n      product {\n        id\n        ...ProductLinkTable\n      }\n    }\n  }\n": typeof types.UpdateProductLinkOnEditProductLinkItemDocument,
    "\n  mutation GenerateProductDescription($input: GenerateProductDescriptionInput!) {\n    generateProductDescription(input: $input) {\n      product {\n        id\n        name\n        description\n      }\n    }\n  }\n": typeof types.GenerateProductDescriptionDocument,
    "\n  mutation IndexProductOnIndexProductButton($input: IndexProductInput!) {\n    indexProduct(input: $input) {\n      indexed\n    }\n  }\n": typeof types.IndexProductOnIndexProductButtonDocument,
    "\n  mutation CreateProductFeatureOnNewProductFeatureForm($input: CreateProductFeatureInput!) {\n    createProductFeature(input: $input) {\n      feature {\n        id\n        name\n      }\n    }\n  }\n": typeof types.CreateProductFeatureOnNewProductFeatureFormDocument,
    "\n  mutation CreateProductOnNewProductForm($input: CreateProductInput!) {\n    createProduct(input: $input) {\n      product {\n        id\n        slug\n      }\n    }\n  }\n": typeof types.CreateProductOnNewProductFormDocument,
    "\n  mutation AddProductLinkOnNewProductLinkForm($slug: String!, $input: AddProductLinkInput!) {\n    addProductLink(slug: $slug, input: $input) {\n      product {\n        id\n        links {\n          id\n          isPrimary\n          title\n          link\n          displayLink\n          iconUrl\n        }\n      }\n    }\n  }\n": typeof types.AddProductLinkOnNewProductLinkFormDocument,
    "\n  mutation AddProductScreenshotOnNewProductScreenshotForm($slug: String!, $input: AddProductScreenshotInput!) {\n    addProductScreenshot(slug: $slug, input: $input) {\n      product {\n        id\n        screenshots {\n          id\n          imageAlt\n          imageUrl\n        }\n      }\n    }\n  }\n": typeof types.AddProductScreenshotOnNewProductScreenshotFormDocument,
    "\n  query TempProductBySlugOnProductCompanyInfo($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      ownedCompany {\n        id\n        name\n        type\n        address\n        startAt\n      }\n    }\n  }\n": typeof types.TempProductBySlugOnProductCompanyInfoDocument,
    "\n  query TempProductBySlugOnProductDescription($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      description\n    }\n  }\n": typeof types.TempProductBySlugOnProductDescriptionDocument,
    "\n  query TempProductBySlugOnProductFeatureTable($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      features {\n        id\n        name\n        emoji\n        summary\n      }\n    }\n  }\n": typeof types.TempProductBySlugOnProductFeatureTableDocument,
    "\n  query TempProductBySlugOnProductInfo($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      name\n      slug\n      summary\n      logoUrl\n    }\n  }\n": typeof types.TempProductBySlugOnProductInfoDocument,
    "\n  fragment ProductLinkTable on Product {\n    links {\n      id\n      isPrimary\n      ...EditProductLinkItem\n    }\n  }\n": typeof types.ProductLinkTableFragmentDoc,
    "\n  query TempProductBySlugOnProductLinkTable($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      ...ProductLinkTable\n    }\n  }\n": typeof types.TempProductBySlugOnProductLinkTableDocument,
    "\n  query AllProductsOnProductListTable($first: Int, $after: String, $last: Int, $before: String) {\n    allProducts(first: $first, after: $after, last: $last, before: $before) {\n      edges {\n        cursor\n        node {\n          id\n          logoUrl\n          slug\n          name\n          summary\n        }\n      }\n      pageInfo {\n        endCursor\n        hasNextPage\n        startCursor\n        hasPreviousPage\n      }\n      totalCount\n    }\n  }\n": typeof types.AllProductsOnProductListTableDocument,
    "\n  query TempProductBySlugOnProductTagsForm($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      tags {\n        id\n        name\n      }\n    }\n  }\n\n  mutation UpdateProductTagsOnProductTagForm($slug: String!, $input: UpdateProductTagsInput!) {\n    updateProductTags(slug: $slug, input: $input) {\n      product {\n        id\n        tags {\n          id\n          name\n        }\n      }\n    }\n  }\n": typeof types.TempProductBySlugOnProductTagsFormDocument,
    "\n  query TempProductOnPublishProductButton($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      publishedAt\n    }\n  }\n  mutation PublishProductOnPublishProductButton($input: PublishProductInput!) {\n    publishProduct(input: $input) {\n      product {\n        id\n        publishedAt\n      }\n    }\n  }\n": typeof types.TempProductOnPublishProductButtonDocument,
    "\n  query SearchProductsOnSearchProductField($query: String!) {\n    searchProducts(query: $query) {\n      id\n      name\n    }\n  }\n": typeof types.SearchProductsOnSearchProductFieldDocument,
    "\n  mutation RequestProductTranslationOnTranslateButton($slug: String!) {\n    requestProductTranslation(slug: $slug) {\n      entityId\n      status\n      message\n    }\n  }\n": typeof types.RequestProductTranslationOnTranslateButtonDocument,
    "\n  query ProductBySlugOnAlternativeProductList($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      alternatives {\n        id\n        name\n        slug\n        summary\n        logoUrl\n        tags {\n          id\n          name\n        }\n      }\n    }\n  }\n": typeof types.ProductBySlugOnAlternativeProductListDocument,
    "\n  query ProductWithFeaturesOnProductAlternativeList($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      alternatives {\n        id\n        slug\n        name\n        logoUrl\n        summary\n        tags {\n          id\n          name\n        }\n        description\n        features {\n          emoji\n          id\n          name\n          summary\n        }\n      }\n    }\n  }\n": typeof types.ProductWithFeaturesOnProductAlternativeListDocument,
    "\n  query ProductBySlugOnProductCompany($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      ownedCompany {\n        id\n        name\n        type\n        address\n        startAt\n      }\n    }\n  }\n": typeof types.ProductBySlugOnProductCompanyDocument,
    "\n  query ProductBySlugOnProductSummary($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      description\n    }\n  }\n": typeof types.ProductBySlugOnProductSummaryDocument,
    "\n  query ProductWithFeaturesOnProductFeatureList($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      features {\n        id\n        name\n        emoji\n        summary\n        screenshots {\n          id\n          imageAlt\n          imageUrl\n        }\n      }\n    }\n  }\n": typeof types.ProductWithFeaturesOnProductFeatureListDocument,
    "\n  query ProductBySlugOnProductInformation($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      name\n      summary\n      description\n      logoUrl\n      tags {\n        id\n        name\n      }\n    }\n  }\n": typeof types.ProductBySlugOnProductInformationDocument,
    "\n  query ProductOnProductLinks($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      links {\n        id\n        displayLink\n        link\n        title\n        iconUrl\n      }\n    }\n  }\n": typeof types.ProductOnProductLinksDocument,
    "\n  query GetPhotosOnProductPhotos($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      screenshots {\n        imageUrl\n        imageAlt\n      }\n    }\n  }\n": typeof types.GetPhotosOnProductPhotosDocument,
    "\n  query ProductBySlugOnProductUserAction($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      name\n      voteCount\n    }\n  }\n  mutation UpvoteProductOnProductUserAction($slug: String!) {\n    upvoteProduct(slug: $slug) {\n      product {\n        id\n        voteCount\n      }\n    }\n  }\n": typeof types.ProductBySlugOnProductUserActionDocument,
    "\n  query ProductsCountOnProductsCount {\n    productsCount\n  }\n": typeof types.ProductsCountOnProductsCountDocument,
    "\n  query RankedProductsOnRankedProductList($locale: String!) {\n    rankedProducts(first: 30, locale: $locale) {\n      id\n      name\n      slug\n      logoUrl\n      summary\n      voteCount\n      tags {\n        id\n        name\n      }\n    }\n  }\n": typeof types.RankedProductsOnRankedProductListDocument,
    "\n  query RecentProductsOnRecentProductList($locale: String!) {\n    recentProducts(first: 8, locale: $locale) {\n      id\n      name\n      slug\n      logoUrl\n      summary\n      tags {\n        id\n        name\n      }\n    }\n  }\n": typeof types.RecentProductsOnRecentProductListDocument,
    "\n  query CategoriesOnCategoryNavigationSection($first: Int!, $locale: String!) {\n    categories(first: $first, locale: $locale) {\n      id\n      slug\n      labelKo\n      labelEn\n    }\n  }\n": typeof types.CategoriesOnCategoryNavigationSectionDocument,
    "\n  query ProductsByCategoryOnSection($slug: String!, $locale: String!) {\n    productsByCategory(slug: $slug, locale: $locale) {\n      id\n      name\n      slug\n      logoUrl\n      summary\n      voteCount\n      tags {\n        id\n        name\n      }\n    }\n    categories(first: 100, locale: $locale) {\n      id\n      slug\n      labelKo\n      labelEn\n    }\n  }\n": typeof types.ProductsByCategoryOnSectionDocument,
    "\n  query RelatedProducts($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      alternatives {\n        id\n        name\n        slug\n        logoUrl\n        summary\n        voteCount\n        tags {\n          id\n          name\n        }\n      }\n    }\n  }\n": typeof types.RelatedProductsDocument,
    "\n  query TrendingProductsOnTrendingProductSection($locale: String!) {\n    rankedProducts(first: 8, locale: $locale) {\n      id\n      name\n      slug\n      logoUrl\n      summary\n      voteCount\n      tags {\n        id\n        name\n      }\n    }\n  }\n": typeof types.TrendingProductsOnTrendingProductSectionDocument,
    "\n  query CompactCategoriesForSearchProductList($first: Int!, $locale: String!) {\n    categories(first: $first, locale: $locale) {\n      id\n      slug\n      labelKo\n      labelEn\n    }\n  }\n": typeof types.CompactCategoriesForSearchProductListDocument,
    "\n  query CompactTrendingPreviewForSearchProductList($first: Int!, $locale: String!) {\n    rankedProducts(first: $first, locale: $locale) {\n      id\n      name\n      slug\n      logoUrl\n      summary\n      voteCount\n      tags {\n        id\n        name\n      }\n    }\n  }\n": typeof types.CompactTrendingPreviewForSearchProductListDocument,
    "\n  query SearchProductsOnSearchProductList($query: String!, $locale: String!) {\n    searchProducts(query: $query, locale: $locale) {\n      id\n      slug\n      name\n      logoUrl\n      summary\n      tags {\n        id\n        name\n      }\n      features {\n        emoji\n        id\n        name\n        summary\n      }\n    }\n  }\n": typeof types.SearchProductsOnSearchProductListDocument,
    "\n  query CategoriesForEmptyState($first: Int!, $locale: String!) {\n    categories(first: $first, locale: $locale) {\n      id\n      slug\n      labelKo\n      labelEn\n    }\n  }\n": typeof types.CategoriesForEmptyStateDocument,
    "\n  query TrendingPreview($first: Int!, $locale: String!) {\n    rankedProducts(first: $first, locale: $locale) {\n      id\n      name\n      slug\n      logoUrl\n      summary\n      voteCount\n      tags {\n        id\n        name\n      }\n    }\n  }\n": typeof types.TrendingPreviewDocument,
    "\n  mutation SignImageUpload($input: SignImageUploadInput!) {\n    signImageUpload(input: $input) {\n      signature\n      folder\n      timestamp\n    }\n  }\n": typeof types.SignImageUploadDocument,
};
const documents: Documents = {
    "\n  query TempAllMagazinesOnMagazinesList($page: Int!) {\n    tempAllMagazines(page: $page) {\n      totalCount\n      totalPages\n      magazines {\n        id\n        slug\n        title\n        summary\n        content\n        backgroundImageUrl\n        updatedAt\n        publishedAt\n        author {\n          id\n          name\n        }\n      }\n    }\n  }\n": types.TempAllMagazinesOnMagazinesListDocument,
    "\n  query GetLlmSettingOnLlmSettingFormSection {\n    llmSetting {\n      id\n      endpoint\n      apiKeyMasked\n      model\n      thinkingLevel\n      updatedAt\n    }\n  }\n": types.GetLlmSettingOnLlmSettingFormSectionDocument,
    "\n  mutation UpdateLlmSettingOnLlmSettingFormSection(\n    $endpoint: String\n    $apiKey: String\n    $model: String\n    $thinkingLevel: String\n  ) {\n    updateLlmSetting(\n      endpoint: $endpoint\n      apiKey: $apiKey\n      model: $model\n      thinkingLevel: $thinkingLevel\n    ) {\n      id\n      endpoint\n      apiKeyMasked\n      model\n      thinkingLevel\n      updatedAt\n    }\n  }\n": types.UpdateLlmSettingOnLlmSettingFormSectionDocument,
    "\n  query CategoryBySlugOnCategoryPageMetadata($first: Int!, $locale: String!) {\n    categories(first: $first, locale: $locale) {\n      id\n      slug\n      labelKo\n      labelEn\n    }\n  }\n": types.CategoryBySlugOnCategoryPageMetadataDocument,
    "\n  query ProductsForCompare($slug1: String!, $slug2: String!, $locale: String!) {\n    product1: productBySlug(slug: $slug1, locale: $locale) {\n      id\n      name\n      slug\n      summary\n      logoUrl\n      voteCount\n      tags {\n        id\n        name\n      }\n      ownedCompany {\n        name\n      }\n    }\n    product2: productBySlug(slug: $slug2, locale: $locale) {\n      id\n      name\n      slug\n      summary\n      logoUrl\n      voteCount\n      tags {\n        id\n        name\n      }\n      ownedCompany {\n        name\n      }\n    }\n  }\n": types.ProductsForCompareDocument,
    "\n  query MagazineBySlugOnMagazinePageMetadata($slug: String!) {\n    magazineBySlug(slug: $slug) {\n      title\n      summary\n      backgroundImageUrl\n      publishedAt\n      updatedAt\n      author {\n        name\n      }\n    }\n  }\n": types.MagazineBySlugOnMagazinePageMetadataDocument,
    "\n  query ProductsCountOnHomePage {\n    productsCount\n  }\n": types.ProductsCountOnHomePageDocument,
    "\n  query ProductBySlugOnProductAlternativePageMetadata($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      name\n      summary\n      logoUrl\n      tags {\n        name\n      }\n      alternatives {\n        name\n        tags {\n          name\n        }\n      }\n    }\n  }\n": types.ProductBySlugOnProductAlternativePageMetadataDocument,
    "\n  query ProductBySlugOnProductDetailPageMetadata($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      name\n      summary\n      logoUrl\n      description\n      tags {\n        name\n      }\n      ownedCompany {\n        name\n      }\n    }\n  }\n": types.ProductBySlugOnProductDetailPageMetadataDocument,
    "\n  query AllCompaniesOnAllCompanyListTable($page: Int!) {\n    allCompanies(page: $page) {\n      totalCount\n      totalPages\n      companies {\n        id\n        name\n        type\n        address\n        startAt\n      }\n    }\n  }\n": types.AllCompaniesOnAllCompanyListTableDocument,
    "\n  mutation CreateCompanyOnNewCompanyForm($input: CreateCompanyInput!) {\n    createCompany(input: $input) {\n      company {\n        id\n      }\n    }\n  }\n": types.CreateCompanyOnNewCompanyFormDocument,
    "\n  mutation CreateMagazineOnWriteMagazine($input: CreateMagazineInput!) {\n    createMagazine(input: $input) {\n      magazine {\n        id\n        slug\n      }\n    }\n  }\n": types.CreateMagazineOnWriteMagazineDocument,
    "\n  query MagazineBySlugOnInfoSection($slug: String!) {\n    magazineBySlug(slug: $slug) {\n      id\n      title\n      summary\n      backgroundImageUrl\n      publishedAt\n      author {\n        name\n      }\n    }\n  }\n": types.MagazineBySlugOnInfoSectionDocument,
    "\n  query TempProductBySlugOnEditAlternativeProducts($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      alternatives {\n        id\n        name\n      }\n    }\n  }\n\n  query SearchProductsOnEditAlternativeProducts($query: String!) {\n    searchProducts(query: $query) {\n      id\n      name\n    }\n  }\n\n  mutation EditProductOnEditAlternativeProducts($input: UpdateAlternativeProductInput!, $slug: String!) {\n    updateAlternativeProduct(input: $input, slug: $slug) {\n      product {\n        id\n        alternatives {\n          id\n        }\n      }\n    }\n  }\n": types.TempProductBySlugOnEditAlternativeProductsDocument,
    "\n  mutation RegisterProductCompanyOnEditProductCompany($input: RegisterProductCompanyInput!, $slug: String!) {\n    registerProductCompany(input: $input, slug: $slug) {\n      product {\n        id\n      }\n    }\n  }\n": types.RegisterProductCompanyOnEditProductCompanyDocument,
    "\n  query SearchCompaniesOnEditProductCompany($query: String!) {\n    searchCompanies(query: $query) {\n      id\n      name\n    }\n  }\n": types.SearchCompaniesOnEditProductCompanyDocument,
    "\n  query TempProductBySlugOnEditProductDescription($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      description\n    }\n  }\n\n  mutation EditProductOnEditProductDescription($input: EditProductInput!, $slug: String!) {\n    editProduct(input: $input, slug: $slug) {\n      product {\n        id\n        description\n      }\n    }\n  }\n": types.TempProductBySlugOnEditProductDescriptionDocument,
    "\n  query FeatureOnEditProductFeatureItem($id: ID!) {\n    feature(id: $id) {\n      id\n      emoji\n      name\n      summary\n    }\n  }\n\n  mutation UpdateProductFeatureOnEditProductFeatureItem($input: UpdateProductFeatureInput!, $featureId: String!) {\n    updateProductFeature(input: $input, id: $featureId) {\n      feature {\n        id\n      }\n    }\n  }\n": types.FeatureOnEditProductFeatureItemDocument,
    "\n  query TempProductBySlugOnEditProductInfo($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      name\n      summary\n    }\n  }\n\n  mutation EditProductOnEditProductInfo($input: EditProductInput!, $slug: String!) {\n    editProduct(input: $input, slug: $slug) {\n      product {\n        id\n        name\n        summary\n      }\n    }\n  }\n": types.TempProductBySlugOnEditProductInfoDocument,
    "\n  fragment EditProductLinkItem on Link {\n    id\n    title\n    link\n    displayLink\n    iconUrl\n  }\n": types.EditProductLinkItemFragmentDoc,
    "\n  mutation UpdateProductLinkOnEditProductLinkItem($slug: String!, $id: String!, $input: UpdateProductLinkInput!) {\n    updateProductLink(slug: $slug, id: $id, input: $input) {\n      product {\n        id\n        ...ProductLinkTable\n      }\n    }\n  }\n": types.UpdateProductLinkOnEditProductLinkItemDocument,
    "\n  mutation GenerateProductDescription($input: GenerateProductDescriptionInput!) {\n    generateProductDescription(input: $input) {\n      product {\n        id\n        name\n        description\n      }\n    }\n  }\n": types.GenerateProductDescriptionDocument,
    "\n  mutation IndexProductOnIndexProductButton($input: IndexProductInput!) {\n    indexProduct(input: $input) {\n      indexed\n    }\n  }\n": types.IndexProductOnIndexProductButtonDocument,
    "\n  mutation CreateProductFeatureOnNewProductFeatureForm($input: CreateProductFeatureInput!) {\n    createProductFeature(input: $input) {\n      feature {\n        id\n        name\n      }\n    }\n  }\n": types.CreateProductFeatureOnNewProductFeatureFormDocument,
    "\n  mutation CreateProductOnNewProductForm($input: CreateProductInput!) {\n    createProduct(input: $input) {\n      product {\n        id\n        slug\n      }\n    }\n  }\n": types.CreateProductOnNewProductFormDocument,
    "\n  mutation AddProductLinkOnNewProductLinkForm($slug: String!, $input: AddProductLinkInput!) {\n    addProductLink(slug: $slug, input: $input) {\n      product {\n        id\n        links {\n          id\n          isPrimary\n          title\n          link\n          displayLink\n          iconUrl\n        }\n      }\n    }\n  }\n": types.AddProductLinkOnNewProductLinkFormDocument,
    "\n  mutation AddProductScreenshotOnNewProductScreenshotForm($slug: String!, $input: AddProductScreenshotInput!) {\n    addProductScreenshot(slug: $slug, input: $input) {\n      product {\n        id\n        screenshots {\n          id\n          imageAlt\n          imageUrl\n        }\n      }\n    }\n  }\n": types.AddProductScreenshotOnNewProductScreenshotFormDocument,
    "\n  query TempProductBySlugOnProductCompanyInfo($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      ownedCompany {\n        id\n        name\n        type\n        address\n        startAt\n      }\n    }\n  }\n": types.TempProductBySlugOnProductCompanyInfoDocument,
    "\n  query TempProductBySlugOnProductDescription($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      description\n    }\n  }\n": types.TempProductBySlugOnProductDescriptionDocument,
    "\n  query TempProductBySlugOnProductFeatureTable($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      features {\n        id\n        name\n        emoji\n        summary\n      }\n    }\n  }\n": types.TempProductBySlugOnProductFeatureTableDocument,
    "\n  query TempProductBySlugOnProductInfo($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      name\n      slug\n      summary\n      logoUrl\n    }\n  }\n": types.TempProductBySlugOnProductInfoDocument,
    "\n  fragment ProductLinkTable on Product {\n    links {\n      id\n      isPrimary\n      ...EditProductLinkItem\n    }\n  }\n": types.ProductLinkTableFragmentDoc,
    "\n  query TempProductBySlugOnProductLinkTable($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      ...ProductLinkTable\n    }\n  }\n": types.TempProductBySlugOnProductLinkTableDocument,
    "\n  query AllProductsOnProductListTable($first: Int, $after: String, $last: Int, $before: String) {\n    allProducts(first: $first, after: $after, last: $last, before: $before) {\n      edges {\n        cursor\n        node {\n          id\n          logoUrl\n          slug\n          name\n          summary\n        }\n      }\n      pageInfo {\n        endCursor\n        hasNextPage\n        startCursor\n        hasPreviousPage\n      }\n      totalCount\n    }\n  }\n": types.AllProductsOnProductListTableDocument,
    "\n  query TempProductBySlugOnProductTagsForm($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      tags {\n        id\n        name\n      }\n    }\n  }\n\n  mutation UpdateProductTagsOnProductTagForm($slug: String!, $input: UpdateProductTagsInput!) {\n    updateProductTags(slug: $slug, input: $input) {\n      product {\n        id\n        tags {\n          id\n          name\n        }\n      }\n    }\n  }\n": types.TempProductBySlugOnProductTagsFormDocument,
    "\n  query TempProductOnPublishProductButton($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      publishedAt\n    }\n  }\n  mutation PublishProductOnPublishProductButton($input: PublishProductInput!) {\n    publishProduct(input: $input) {\n      product {\n        id\n        publishedAt\n      }\n    }\n  }\n": types.TempProductOnPublishProductButtonDocument,
    "\n  query SearchProductsOnSearchProductField($query: String!) {\n    searchProducts(query: $query) {\n      id\n      name\n    }\n  }\n": types.SearchProductsOnSearchProductFieldDocument,
    "\n  mutation RequestProductTranslationOnTranslateButton($slug: String!) {\n    requestProductTranslation(slug: $slug) {\n      entityId\n      status\n      message\n    }\n  }\n": types.RequestProductTranslationOnTranslateButtonDocument,
    "\n  query ProductBySlugOnAlternativeProductList($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      alternatives {\n        id\n        name\n        slug\n        summary\n        logoUrl\n        tags {\n          id\n          name\n        }\n      }\n    }\n  }\n": types.ProductBySlugOnAlternativeProductListDocument,
    "\n  query ProductWithFeaturesOnProductAlternativeList($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      alternatives {\n        id\n        slug\n        name\n        logoUrl\n        summary\n        tags {\n          id\n          name\n        }\n        description\n        features {\n          emoji\n          id\n          name\n          summary\n        }\n      }\n    }\n  }\n": types.ProductWithFeaturesOnProductAlternativeListDocument,
    "\n  query ProductBySlugOnProductCompany($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      ownedCompany {\n        id\n        name\n        type\n        address\n        startAt\n      }\n    }\n  }\n": types.ProductBySlugOnProductCompanyDocument,
    "\n  query ProductBySlugOnProductSummary($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      description\n    }\n  }\n": types.ProductBySlugOnProductSummaryDocument,
    "\n  query ProductWithFeaturesOnProductFeatureList($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      features {\n        id\n        name\n        emoji\n        summary\n        screenshots {\n          id\n          imageAlt\n          imageUrl\n        }\n      }\n    }\n  }\n": types.ProductWithFeaturesOnProductFeatureListDocument,
    "\n  query ProductBySlugOnProductInformation($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      name\n      summary\n      description\n      logoUrl\n      tags {\n        id\n        name\n      }\n    }\n  }\n": types.ProductBySlugOnProductInformationDocument,
    "\n  query ProductOnProductLinks($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      links {\n        id\n        displayLink\n        link\n        title\n        iconUrl\n      }\n    }\n  }\n": types.ProductOnProductLinksDocument,
    "\n  query GetPhotosOnProductPhotos($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      screenshots {\n        imageUrl\n        imageAlt\n      }\n    }\n  }\n": types.GetPhotosOnProductPhotosDocument,
    "\n  query ProductBySlugOnProductUserAction($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      name\n      voteCount\n    }\n  }\n  mutation UpvoteProductOnProductUserAction($slug: String!) {\n    upvoteProduct(slug: $slug) {\n      product {\n        id\n        voteCount\n      }\n    }\n  }\n": types.ProductBySlugOnProductUserActionDocument,
    "\n  query ProductsCountOnProductsCount {\n    productsCount\n  }\n": types.ProductsCountOnProductsCountDocument,
    "\n  query RankedProductsOnRankedProductList($locale: String!) {\n    rankedProducts(first: 30, locale: $locale) {\n      id\n      name\n      slug\n      logoUrl\n      summary\n      voteCount\n      tags {\n        id\n        name\n      }\n    }\n  }\n": types.RankedProductsOnRankedProductListDocument,
    "\n  query RecentProductsOnRecentProductList($locale: String!) {\n    recentProducts(first: 8, locale: $locale) {\n      id\n      name\n      slug\n      logoUrl\n      summary\n      tags {\n        id\n        name\n      }\n    }\n  }\n": types.RecentProductsOnRecentProductListDocument,
    "\n  query CategoriesOnCategoryNavigationSection($first: Int!, $locale: String!) {\n    categories(first: $first, locale: $locale) {\n      id\n      slug\n      labelKo\n      labelEn\n    }\n  }\n": types.CategoriesOnCategoryNavigationSectionDocument,
    "\n  query ProductsByCategoryOnSection($slug: String!, $locale: String!) {\n    productsByCategory(slug: $slug, locale: $locale) {\n      id\n      name\n      slug\n      logoUrl\n      summary\n      voteCount\n      tags {\n        id\n        name\n      }\n    }\n    categories(first: 100, locale: $locale) {\n      id\n      slug\n      labelKo\n      labelEn\n    }\n  }\n": types.ProductsByCategoryOnSectionDocument,
    "\n  query RelatedProducts($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      alternatives {\n        id\n        name\n        slug\n        logoUrl\n        summary\n        voteCount\n        tags {\n          id\n          name\n        }\n      }\n    }\n  }\n": types.RelatedProductsDocument,
    "\n  query TrendingProductsOnTrendingProductSection($locale: String!) {\n    rankedProducts(first: 8, locale: $locale) {\n      id\n      name\n      slug\n      logoUrl\n      summary\n      voteCount\n      tags {\n        id\n        name\n      }\n    }\n  }\n": types.TrendingProductsOnTrendingProductSectionDocument,
    "\n  query CompactCategoriesForSearchProductList($first: Int!, $locale: String!) {\n    categories(first: $first, locale: $locale) {\n      id\n      slug\n      labelKo\n      labelEn\n    }\n  }\n": types.CompactCategoriesForSearchProductListDocument,
    "\n  query CompactTrendingPreviewForSearchProductList($first: Int!, $locale: String!) {\n    rankedProducts(first: $first, locale: $locale) {\n      id\n      name\n      slug\n      logoUrl\n      summary\n      voteCount\n      tags {\n        id\n        name\n      }\n    }\n  }\n": types.CompactTrendingPreviewForSearchProductListDocument,
    "\n  query SearchProductsOnSearchProductList($query: String!, $locale: String!) {\n    searchProducts(query: $query, locale: $locale) {\n      id\n      slug\n      name\n      logoUrl\n      summary\n      tags {\n        id\n        name\n      }\n      features {\n        emoji\n        id\n        name\n        summary\n      }\n    }\n  }\n": types.SearchProductsOnSearchProductListDocument,
    "\n  query CategoriesForEmptyState($first: Int!, $locale: String!) {\n    categories(first: $first, locale: $locale) {\n      id\n      slug\n      labelKo\n      labelEn\n    }\n  }\n": types.CategoriesForEmptyStateDocument,
    "\n  query TrendingPreview($first: Int!, $locale: String!) {\n    rankedProducts(first: $first, locale: $locale) {\n      id\n      name\n      slug\n      logoUrl\n      summary\n      voteCount\n      tags {\n        id\n        name\n      }\n    }\n  }\n": types.TrendingPreviewDocument,
    "\n  mutation SignImageUpload($input: SignImageUploadInput!) {\n    signImageUpload(input: $input) {\n      signature\n      folder\n      timestamp\n    }\n  }\n": types.SignImageUploadDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query TempAllMagazinesOnMagazinesList($page: Int!) {\n    tempAllMagazines(page: $page) {\n      totalCount\n      totalPages\n      magazines {\n        id\n        slug\n        title\n        summary\n        content\n        backgroundImageUrl\n        updatedAt\n        publishedAt\n        author {\n          id\n          name\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query TempAllMagazinesOnMagazinesList($page: Int!) {\n    tempAllMagazines(page: $page) {\n      totalCount\n      totalPages\n      magazines {\n        id\n        slug\n        title\n        summary\n        content\n        backgroundImageUrl\n        updatedAt\n        publishedAt\n        author {\n          id\n          name\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetLlmSettingOnLlmSettingFormSection {\n    llmSetting {\n      id\n      endpoint\n      apiKeyMasked\n      model\n      thinkingLevel\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query GetLlmSettingOnLlmSettingFormSection {\n    llmSetting {\n      id\n      endpoint\n      apiKeyMasked\n      model\n      thinkingLevel\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdateLlmSettingOnLlmSettingFormSection(\n    $endpoint: String\n    $apiKey: String\n    $model: String\n    $thinkingLevel: String\n  ) {\n    updateLlmSetting(\n      endpoint: $endpoint\n      apiKey: $apiKey\n      model: $model\n      thinkingLevel: $thinkingLevel\n    ) {\n      id\n      endpoint\n      apiKeyMasked\n      model\n      thinkingLevel\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateLlmSettingOnLlmSettingFormSection(\n    $endpoint: String\n    $apiKey: String\n    $model: String\n    $thinkingLevel: String\n  ) {\n    updateLlmSetting(\n      endpoint: $endpoint\n      apiKey: $apiKey\n      model: $model\n      thinkingLevel: $thinkingLevel\n    ) {\n      id\n      endpoint\n      apiKeyMasked\n      model\n      thinkingLevel\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query CategoryBySlugOnCategoryPageMetadata($first: Int!, $locale: String!) {\n    categories(first: $first, locale: $locale) {\n      id\n      slug\n      labelKo\n      labelEn\n    }\n  }\n"): (typeof documents)["\n  query CategoryBySlugOnCategoryPageMetadata($first: Int!, $locale: String!) {\n    categories(first: $first, locale: $locale) {\n      id\n      slug\n      labelKo\n      labelEn\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ProductsForCompare($slug1: String!, $slug2: String!, $locale: String!) {\n    product1: productBySlug(slug: $slug1, locale: $locale) {\n      id\n      name\n      slug\n      summary\n      logoUrl\n      voteCount\n      tags {\n        id\n        name\n      }\n      ownedCompany {\n        name\n      }\n    }\n    product2: productBySlug(slug: $slug2, locale: $locale) {\n      id\n      name\n      slug\n      summary\n      logoUrl\n      voteCount\n      tags {\n        id\n        name\n      }\n      ownedCompany {\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  query ProductsForCompare($slug1: String!, $slug2: String!, $locale: String!) {\n    product1: productBySlug(slug: $slug1, locale: $locale) {\n      id\n      name\n      slug\n      summary\n      logoUrl\n      voteCount\n      tags {\n        id\n        name\n      }\n      ownedCompany {\n        name\n      }\n    }\n    product2: productBySlug(slug: $slug2, locale: $locale) {\n      id\n      name\n      slug\n      summary\n      logoUrl\n      voteCount\n      tags {\n        id\n        name\n      }\n      ownedCompany {\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query MagazineBySlugOnMagazinePageMetadata($slug: String!) {\n    magazineBySlug(slug: $slug) {\n      title\n      summary\n      backgroundImageUrl\n      publishedAt\n      updatedAt\n      author {\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  query MagazineBySlugOnMagazinePageMetadata($slug: String!) {\n    magazineBySlug(slug: $slug) {\n      title\n      summary\n      backgroundImageUrl\n      publishedAt\n      updatedAt\n      author {\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ProductsCountOnHomePage {\n    productsCount\n  }\n"): (typeof documents)["\n  query ProductsCountOnHomePage {\n    productsCount\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ProductBySlugOnProductAlternativePageMetadata($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      name\n      summary\n      logoUrl\n      tags {\n        name\n      }\n      alternatives {\n        name\n        tags {\n          name\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query ProductBySlugOnProductAlternativePageMetadata($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      name\n      summary\n      logoUrl\n      tags {\n        name\n      }\n      alternatives {\n        name\n        tags {\n          name\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ProductBySlugOnProductDetailPageMetadata($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      name\n      summary\n      logoUrl\n      description\n      tags {\n        name\n      }\n      ownedCompany {\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  query ProductBySlugOnProductDetailPageMetadata($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      name\n      summary\n      logoUrl\n      description\n      tags {\n        name\n      }\n      ownedCompany {\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query AllCompaniesOnAllCompanyListTable($page: Int!) {\n    allCompanies(page: $page) {\n      totalCount\n      totalPages\n      companies {\n        id\n        name\n        type\n        address\n        startAt\n      }\n    }\n  }\n"): (typeof documents)["\n  query AllCompaniesOnAllCompanyListTable($page: Int!) {\n    allCompanies(page: $page) {\n      totalCount\n      totalPages\n      companies {\n        id\n        name\n        type\n        address\n        startAt\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateCompanyOnNewCompanyForm($input: CreateCompanyInput!) {\n    createCompany(input: $input) {\n      company {\n        id\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation CreateCompanyOnNewCompanyForm($input: CreateCompanyInput!) {\n    createCompany(input: $input) {\n      company {\n        id\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateMagazineOnWriteMagazine($input: CreateMagazineInput!) {\n    createMagazine(input: $input) {\n      magazine {\n        id\n        slug\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation CreateMagazineOnWriteMagazine($input: CreateMagazineInput!) {\n    createMagazine(input: $input) {\n      magazine {\n        id\n        slug\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query MagazineBySlugOnInfoSection($slug: String!) {\n    magazineBySlug(slug: $slug) {\n      id\n      title\n      summary\n      backgroundImageUrl\n      publishedAt\n      author {\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  query MagazineBySlugOnInfoSection($slug: String!) {\n    magazineBySlug(slug: $slug) {\n      id\n      title\n      summary\n      backgroundImageUrl\n      publishedAt\n      author {\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query TempProductBySlugOnEditAlternativeProducts($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      alternatives {\n        id\n        name\n      }\n    }\n  }\n\n  query SearchProductsOnEditAlternativeProducts($query: String!) {\n    searchProducts(query: $query) {\n      id\n      name\n    }\n  }\n\n  mutation EditProductOnEditAlternativeProducts($input: UpdateAlternativeProductInput!, $slug: String!) {\n    updateAlternativeProduct(input: $input, slug: $slug) {\n      product {\n        id\n        alternatives {\n          id\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query TempProductBySlugOnEditAlternativeProducts($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      alternatives {\n        id\n        name\n      }\n    }\n  }\n\n  query SearchProductsOnEditAlternativeProducts($query: String!) {\n    searchProducts(query: $query) {\n      id\n      name\n    }\n  }\n\n  mutation EditProductOnEditAlternativeProducts($input: UpdateAlternativeProductInput!, $slug: String!) {\n    updateAlternativeProduct(input: $input, slug: $slug) {\n      product {\n        id\n        alternatives {\n          id\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation RegisterProductCompanyOnEditProductCompany($input: RegisterProductCompanyInput!, $slug: String!) {\n    registerProductCompany(input: $input, slug: $slug) {\n      product {\n        id\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation RegisterProductCompanyOnEditProductCompany($input: RegisterProductCompanyInput!, $slug: String!) {\n    registerProductCompany(input: $input, slug: $slug) {\n      product {\n        id\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query SearchCompaniesOnEditProductCompany($query: String!) {\n    searchCompanies(query: $query) {\n      id\n      name\n    }\n  }\n"): (typeof documents)["\n  query SearchCompaniesOnEditProductCompany($query: String!) {\n    searchCompanies(query: $query) {\n      id\n      name\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query TempProductBySlugOnEditProductDescription($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      description\n    }\n  }\n\n  mutation EditProductOnEditProductDescription($input: EditProductInput!, $slug: String!) {\n    editProduct(input: $input, slug: $slug) {\n      product {\n        id\n        description\n      }\n    }\n  }\n"): (typeof documents)["\n  query TempProductBySlugOnEditProductDescription($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      description\n    }\n  }\n\n  mutation EditProductOnEditProductDescription($input: EditProductInput!, $slug: String!) {\n    editProduct(input: $input, slug: $slug) {\n      product {\n        id\n        description\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query FeatureOnEditProductFeatureItem($id: ID!) {\n    feature(id: $id) {\n      id\n      emoji\n      name\n      summary\n    }\n  }\n\n  mutation UpdateProductFeatureOnEditProductFeatureItem($input: UpdateProductFeatureInput!, $featureId: String!) {\n    updateProductFeature(input: $input, id: $featureId) {\n      feature {\n        id\n      }\n    }\n  }\n"): (typeof documents)["\n  query FeatureOnEditProductFeatureItem($id: ID!) {\n    feature(id: $id) {\n      id\n      emoji\n      name\n      summary\n    }\n  }\n\n  mutation UpdateProductFeatureOnEditProductFeatureItem($input: UpdateProductFeatureInput!, $featureId: String!) {\n    updateProductFeature(input: $input, id: $featureId) {\n      feature {\n        id\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query TempProductBySlugOnEditProductInfo($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      name\n      summary\n    }\n  }\n\n  mutation EditProductOnEditProductInfo($input: EditProductInput!, $slug: String!) {\n    editProduct(input: $input, slug: $slug) {\n      product {\n        id\n        name\n        summary\n      }\n    }\n  }\n"): (typeof documents)["\n  query TempProductBySlugOnEditProductInfo($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      name\n      summary\n    }\n  }\n\n  mutation EditProductOnEditProductInfo($input: EditProductInput!, $slug: String!) {\n    editProduct(input: $input, slug: $slug) {\n      product {\n        id\n        name\n        summary\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment EditProductLinkItem on Link {\n    id\n    title\n    link\n    displayLink\n    iconUrl\n  }\n"): (typeof documents)["\n  fragment EditProductLinkItem on Link {\n    id\n    title\n    link\n    displayLink\n    iconUrl\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdateProductLinkOnEditProductLinkItem($slug: String!, $id: String!, $input: UpdateProductLinkInput!) {\n    updateProductLink(slug: $slug, id: $id, input: $input) {\n      product {\n        id\n        ...ProductLinkTable\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateProductLinkOnEditProductLinkItem($slug: String!, $id: String!, $input: UpdateProductLinkInput!) {\n    updateProductLink(slug: $slug, id: $id, input: $input) {\n      product {\n        id\n        ...ProductLinkTable\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation GenerateProductDescription($input: GenerateProductDescriptionInput!) {\n    generateProductDescription(input: $input) {\n      product {\n        id\n        name\n        description\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation GenerateProductDescription($input: GenerateProductDescriptionInput!) {\n    generateProductDescription(input: $input) {\n      product {\n        id\n        name\n        description\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation IndexProductOnIndexProductButton($input: IndexProductInput!) {\n    indexProduct(input: $input) {\n      indexed\n    }\n  }\n"): (typeof documents)["\n  mutation IndexProductOnIndexProductButton($input: IndexProductInput!) {\n    indexProduct(input: $input) {\n      indexed\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateProductFeatureOnNewProductFeatureForm($input: CreateProductFeatureInput!) {\n    createProductFeature(input: $input) {\n      feature {\n        id\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation CreateProductFeatureOnNewProductFeatureForm($input: CreateProductFeatureInput!) {\n    createProductFeature(input: $input) {\n      feature {\n        id\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateProductOnNewProductForm($input: CreateProductInput!) {\n    createProduct(input: $input) {\n      product {\n        id\n        slug\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation CreateProductOnNewProductForm($input: CreateProductInput!) {\n    createProduct(input: $input) {\n      product {\n        id\n        slug\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation AddProductLinkOnNewProductLinkForm($slug: String!, $input: AddProductLinkInput!) {\n    addProductLink(slug: $slug, input: $input) {\n      product {\n        id\n        links {\n          id\n          isPrimary\n          title\n          link\n          displayLink\n          iconUrl\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation AddProductLinkOnNewProductLinkForm($slug: String!, $input: AddProductLinkInput!) {\n    addProductLink(slug: $slug, input: $input) {\n      product {\n        id\n        links {\n          id\n          isPrimary\n          title\n          link\n          displayLink\n          iconUrl\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation AddProductScreenshotOnNewProductScreenshotForm($slug: String!, $input: AddProductScreenshotInput!) {\n    addProductScreenshot(slug: $slug, input: $input) {\n      product {\n        id\n        screenshots {\n          id\n          imageAlt\n          imageUrl\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation AddProductScreenshotOnNewProductScreenshotForm($slug: String!, $input: AddProductScreenshotInput!) {\n    addProductScreenshot(slug: $slug, input: $input) {\n      product {\n        id\n        screenshots {\n          id\n          imageAlt\n          imageUrl\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query TempProductBySlugOnProductCompanyInfo($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      ownedCompany {\n        id\n        name\n        type\n        address\n        startAt\n      }\n    }\n  }\n"): (typeof documents)["\n  query TempProductBySlugOnProductCompanyInfo($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      ownedCompany {\n        id\n        name\n        type\n        address\n        startAt\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query TempProductBySlugOnProductDescription($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      description\n    }\n  }\n"): (typeof documents)["\n  query TempProductBySlugOnProductDescription($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      description\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query TempProductBySlugOnProductFeatureTable($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      features {\n        id\n        name\n        emoji\n        summary\n      }\n    }\n  }\n"): (typeof documents)["\n  query TempProductBySlugOnProductFeatureTable($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      features {\n        id\n        name\n        emoji\n        summary\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query TempProductBySlugOnProductInfo($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      name\n      slug\n      summary\n      logoUrl\n    }\n  }\n"): (typeof documents)["\n  query TempProductBySlugOnProductInfo($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      name\n      slug\n      summary\n      logoUrl\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment ProductLinkTable on Product {\n    links {\n      id\n      isPrimary\n      ...EditProductLinkItem\n    }\n  }\n"): (typeof documents)["\n  fragment ProductLinkTable on Product {\n    links {\n      id\n      isPrimary\n      ...EditProductLinkItem\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query TempProductBySlugOnProductLinkTable($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      ...ProductLinkTable\n    }\n  }\n"): (typeof documents)["\n  query TempProductBySlugOnProductLinkTable($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      ...ProductLinkTable\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query AllProductsOnProductListTable($first: Int, $after: String, $last: Int, $before: String) {\n    allProducts(first: $first, after: $after, last: $last, before: $before) {\n      edges {\n        cursor\n        node {\n          id\n          logoUrl\n          slug\n          name\n          summary\n        }\n      }\n      pageInfo {\n        endCursor\n        hasNextPage\n        startCursor\n        hasPreviousPage\n      }\n      totalCount\n    }\n  }\n"): (typeof documents)["\n  query AllProductsOnProductListTable($first: Int, $after: String, $last: Int, $before: String) {\n    allProducts(first: $first, after: $after, last: $last, before: $before) {\n      edges {\n        cursor\n        node {\n          id\n          logoUrl\n          slug\n          name\n          summary\n        }\n      }\n      pageInfo {\n        endCursor\n        hasNextPage\n        startCursor\n        hasPreviousPage\n      }\n      totalCount\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query TempProductBySlugOnProductTagsForm($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      tags {\n        id\n        name\n      }\n    }\n  }\n\n  mutation UpdateProductTagsOnProductTagForm($slug: String!, $input: UpdateProductTagsInput!) {\n    updateProductTags(slug: $slug, input: $input) {\n      product {\n        id\n        tags {\n          id\n          name\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query TempProductBySlugOnProductTagsForm($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      tags {\n        id\n        name\n      }\n    }\n  }\n\n  mutation UpdateProductTagsOnProductTagForm($slug: String!, $input: UpdateProductTagsInput!) {\n    updateProductTags(slug: $slug, input: $input) {\n      product {\n        id\n        tags {\n          id\n          name\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query TempProductOnPublishProductButton($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      publishedAt\n    }\n  }\n  mutation PublishProductOnPublishProductButton($input: PublishProductInput!) {\n    publishProduct(input: $input) {\n      product {\n        id\n        publishedAt\n      }\n    }\n  }\n"): (typeof documents)["\n  query TempProductOnPublishProductButton($slug: String!) {\n    tempProductBySlug(slug: $slug) {\n      id\n      publishedAt\n    }\n  }\n  mutation PublishProductOnPublishProductButton($input: PublishProductInput!) {\n    publishProduct(input: $input) {\n      product {\n        id\n        publishedAt\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query SearchProductsOnSearchProductField($query: String!) {\n    searchProducts(query: $query) {\n      id\n      name\n    }\n  }\n"): (typeof documents)["\n  query SearchProductsOnSearchProductField($query: String!) {\n    searchProducts(query: $query) {\n      id\n      name\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation RequestProductTranslationOnTranslateButton($slug: String!) {\n    requestProductTranslation(slug: $slug) {\n      entityId\n      status\n      message\n    }\n  }\n"): (typeof documents)["\n  mutation RequestProductTranslationOnTranslateButton($slug: String!) {\n    requestProductTranslation(slug: $slug) {\n      entityId\n      status\n      message\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ProductBySlugOnAlternativeProductList($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      alternatives {\n        id\n        name\n        slug\n        summary\n        logoUrl\n        tags {\n          id\n          name\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query ProductBySlugOnAlternativeProductList($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      alternatives {\n        id\n        name\n        slug\n        summary\n        logoUrl\n        tags {\n          id\n          name\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ProductWithFeaturesOnProductAlternativeList($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      alternatives {\n        id\n        slug\n        name\n        logoUrl\n        summary\n        tags {\n          id\n          name\n        }\n        description\n        features {\n          emoji\n          id\n          name\n          summary\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query ProductWithFeaturesOnProductAlternativeList($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      alternatives {\n        id\n        slug\n        name\n        logoUrl\n        summary\n        tags {\n          id\n          name\n        }\n        description\n        features {\n          emoji\n          id\n          name\n          summary\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ProductBySlugOnProductCompany($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      ownedCompany {\n        id\n        name\n        type\n        address\n        startAt\n      }\n    }\n  }\n"): (typeof documents)["\n  query ProductBySlugOnProductCompany($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      ownedCompany {\n        id\n        name\n        type\n        address\n        startAt\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ProductBySlugOnProductSummary($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      description\n    }\n  }\n"): (typeof documents)["\n  query ProductBySlugOnProductSummary($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      description\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ProductWithFeaturesOnProductFeatureList($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      features {\n        id\n        name\n        emoji\n        summary\n        screenshots {\n          id\n          imageAlt\n          imageUrl\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query ProductWithFeaturesOnProductFeatureList($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      features {\n        id\n        name\n        emoji\n        summary\n        screenshots {\n          id\n          imageAlt\n          imageUrl\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ProductBySlugOnProductInformation($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      name\n      summary\n      description\n      logoUrl\n      tags {\n        id\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  query ProductBySlugOnProductInformation($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      name\n      summary\n      description\n      logoUrl\n      tags {\n        id\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ProductOnProductLinks($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      links {\n        id\n        displayLink\n        link\n        title\n        iconUrl\n      }\n    }\n  }\n"): (typeof documents)["\n  query ProductOnProductLinks($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      links {\n        id\n        displayLink\n        link\n        title\n        iconUrl\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetPhotosOnProductPhotos($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      screenshots {\n        imageUrl\n        imageAlt\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetPhotosOnProductPhotos($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      screenshots {\n        imageUrl\n        imageAlt\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ProductBySlugOnProductUserAction($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      name\n      voteCount\n    }\n  }\n  mutation UpvoteProductOnProductUserAction($slug: String!) {\n    upvoteProduct(slug: $slug) {\n      product {\n        id\n        voteCount\n      }\n    }\n  }\n"): (typeof documents)["\n  query ProductBySlugOnProductUserAction($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      id\n      name\n      voteCount\n    }\n  }\n  mutation UpvoteProductOnProductUserAction($slug: String!) {\n    upvoteProduct(slug: $slug) {\n      product {\n        id\n        voteCount\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ProductsCountOnProductsCount {\n    productsCount\n  }\n"): (typeof documents)["\n  query ProductsCountOnProductsCount {\n    productsCount\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query RankedProductsOnRankedProductList($locale: String!) {\n    rankedProducts(first: 30, locale: $locale) {\n      id\n      name\n      slug\n      logoUrl\n      summary\n      voteCount\n      tags {\n        id\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  query RankedProductsOnRankedProductList($locale: String!) {\n    rankedProducts(first: 30, locale: $locale) {\n      id\n      name\n      slug\n      logoUrl\n      summary\n      voteCount\n      tags {\n        id\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query RecentProductsOnRecentProductList($locale: String!) {\n    recentProducts(first: 8, locale: $locale) {\n      id\n      name\n      slug\n      logoUrl\n      summary\n      tags {\n        id\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  query RecentProductsOnRecentProductList($locale: String!) {\n    recentProducts(first: 8, locale: $locale) {\n      id\n      name\n      slug\n      logoUrl\n      summary\n      tags {\n        id\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query CategoriesOnCategoryNavigationSection($first: Int!, $locale: String!) {\n    categories(first: $first, locale: $locale) {\n      id\n      slug\n      labelKo\n      labelEn\n    }\n  }\n"): (typeof documents)["\n  query CategoriesOnCategoryNavigationSection($first: Int!, $locale: String!) {\n    categories(first: $first, locale: $locale) {\n      id\n      slug\n      labelKo\n      labelEn\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ProductsByCategoryOnSection($slug: String!, $locale: String!) {\n    productsByCategory(slug: $slug, locale: $locale) {\n      id\n      name\n      slug\n      logoUrl\n      summary\n      voteCount\n      tags {\n        id\n        name\n      }\n    }\n    categories(first: 100, locale: $locale) {\n      id\n      slug\n      labelKo\n      labelEn\n    }\n  }\n"): (typeof documents)["\n  query ProductsByCategoryOnSection($slug: String!, $locale: String!) {\n    productsByCategory(slug: $slug, locale: $locale) {\n      id\n      name\n      slug\n      logoUrl\n      summary\n      voteCount\n      tags {\n        id\n        name\n      }\n    }\n    categories(first: 100, locale: $locale) {\n      id\n      slug\n      labelKo\n      labelEn\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query RelatedProducts($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      alternatives {\n        id\n        name\n        slug\n        logoUrl\n        summary\n        voteCount\n        tags {\n          id\n          name\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query RelatedProducts($slug: String!, $locale: String!) {\n    productBySlug(slug: $slug, locale: $locale) {\n      alternatives {\n        id\n        name\n        slug\n        logoUrl\n        summary\n        voteCount\n        tags {\n          id\n          name\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query TrendingProductsOnTrendingProductSection($locale: String!) {\n    rankedProducts(first: 8, locale: $locale) {\n      id\n      name\n      slug\n      logoUrl\n      summary\n      voteCount\n      tags {\n        id\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  query TrendingProductsOnTrendingProductSection($locale: String!) {\n    rankedProducts(first: 8, locale: $locale) {\n      id\n      name\n      slug\n      logoUrl\n      summary\n      voteCount\n      tags {\n        id\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query CompactCategoriesForSearchProductList($first: Int!, $locale: String!) {\n    categories(first: $first, locale: $locale) {\n      id\n      slug\n      labelKo\n      labelEn\n    }\n  }\n"): (typeof documents)["\n  query CompactCategoriesForSearchProductList($first: Int!, $locale: String!) {\n    categories(first: $first, locale: $locale) {\n      id\n      slug\n      labelKo\n      labelEn\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query CompactTrendingPreviewForSearchProductList($first: Int!, $locale: String!) {\n    rankedProducts(first: $first, locale: $locale) {\n      id\n      name\n      slug\n      logoUrl\n      summary\n      voteCount\n      tags {\n        id\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  query CompactTrendingPreviewForSearchProductList($first: Int!, $locale: String!) {\n    rankedProducts(first: $first, locale: $locale) {\n      id\n      name\n      slug\n      logoUrl\n      summary\n      voteCount\n      tags {\n        id\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query SearchProductsOnSearchProductList($query: String!, $locale: String!) {\n    searchProducts(query: $query, locale: $locale) {\n      id\n      slug\n      name\n      logoUrl\n      summary\n      tags {\n        id\n        name\n      }\n      features {\n        emoji\n        id\n        name\n        summary\n      }\n    }\n  }\n"): (typeof documents)["\n  query SearchProductsOnSearchProductList($query: String!, $locale: String!) {\n    searchProducts(query: $query, locale: $locale) {\n      id\n      slug\n      name\n      logoUrl\n      summary\n      tags {\n        id\n        name\n      }\n      features {\n        emoji\n        id\n        name\n        summary\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query CategoriesForEmptyState($first: Int!, $locale: String!) {\n    categories(first: $first, locale: $locale) {\n      id\n      slug\n      labelKo\n      labelEn\n    }\n  }\n"): (typeof documents)["\n  query CategoriesForEmptyState($first: Int!, $locale: String!) {\n    categories(first: $first, locale: $locale) {\n      id\n      slug\n      labelKo\n      labelEn\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query TrendingPreview($first: Int!, $locale: String!) {\n    rankedProducts(first: $first, locale: $locale) {\n      id\n      name\n      slug\n      logoUrl\n      summary\n      voteCount\n      tags {\n        id\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  query TrendingPreview($first: Int!, $locale: String!) {\n    rankedProducts(first: $first, locale: $locale) {\n      id\n      name\n      slug\n      logoUrl\n      summary\n      voteCount\n      tags {\n        id\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation SignImageUpload($input: SignImageUploadInput!) {\n    signImageUpload(input: $input) {\n      signature\n      folder\n      timestamp\n    }\n  }\n"): (typeof documents)["\n  mutation SignImageUpload($input: SignImageUploadInput!) {\n    signImageUpload(input: $input) {\n      signature\n      folder\n      timestamp\n    }\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;