service: darun
frameworkVersion: '3'

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  stackName: ${self:provider.stage}-${self:service}
  stage: ${opt:stage, 'dev'}
  profile: darun
  deploymentBucket: ${self:provider.stage}-${self:service}-deploy-bucket

functions:
  graphql:
    handler: src/functions/graphql.handler
    events:
      - httpApi:
          path: /graphql
          method: post