service: darun
frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    bundle: true
    exclude: ['class-validator']
    minify: false
    keepNames: true
    sourcemap: true
    sourcesContent: false
    treeShaking: false
    ignoreAnnotations: true
    plugins: esbuild.plugins.js
  serverless-offline:
    httpPort: 4000

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  stackName: ${self:provider.stage}-${self:service}
  stage: ${opt:stage, 'dev'}
  profile: darun
  deploymentBucket: ${self:provider.stage}-${self:service}-deploy-bucket
  architecture: arm64
  logRetentionInDays: 7

functions:
  graphql:
    handler: src/functions/graphql.handler
    events:
      - httpApi:
          path: /graphql
          method: post
      - httpApi:
          path: /graphql
          method: get
    environment:
      INFRA_ENV: ${env:INFRA_ENV}
      DATABASE_URL: ${env:DATABASE_URL}
      FIREBASE_PROJECT_ID: ${env:FIREBASE_PROJECT_ID}
      FIREBASE_PRIVATE_KEY: ${env:FIREBASE_PRIVATE_KEY}
      FIREBASE_CLIENT_EMAIL: ${env:FIREBASE_CLIENT_EMAIL}
      MONGODB_URI: ${env:MONGODB_URI}
