service: darun
frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    exclude: ['class-validator']
  serverless-offline:
    reloadHandler: true
    httpPort: 4000

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  stackName: ${self:provider.stage}-${self:service}
  stage: ${opt:stage, 'dev'}
  profile: darun
  deploymentBucket: ${self:provider.stage}-${self:service}-deploy-bucket

functions:
  graphql:
    handler: src/functions/graphql.handler
    events:
      - httpApi:
          path: /graphql
          method: post
      - httpApi:
          path: /graphql
          method: get
    environment:
      INFRA_ENV: ${env:INFRA_ENV}
      DATABASE_URL: ${env:DATABASE_URL}
      DATABASE_USERNAME: ${env:DATABASE_USERNAME}
      DATABASE_PASSWORD: ${env:DATABASE_PASSWORD}