name: Production Deploy

on:
  workflow_dispatch:
    inputs:
      commitHash:
        description: '배포할 커밋해시'
        required: true
        type: string
  repository_dispatch:
    types: [TRIGGER_DEPLOY]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment:
      name: prod-graphql
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Configure AWS Profile iam
        uses: croco-dev/aws-profile-action@v1.3
        with:
          profile: darun
          region: ap-northeast-2
          access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy
        run: pnpm run --F graphql-api deploy:prod
        env:
          INFRA_ENV: prod
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
